#!/bin/bash
#
################################################################################
#
#      Copyright (C) 2017 Josh Sunnex (jsunnex@gmail.com)
#
#  This program is dual-licensed; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this file; see the file COPYING.  If not, see
#  <http://www.gnu.org/licenses/>.
#
################################################################################

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"



function install_python {
    echo "###########################################"
    echo "##     Updating python requirements      ##"
    echo "###########################################"
    sudo -H pip3 install -r ${DIR}/extensions/requirements.txt 
}


function install_link {
    echo "###########################################"
    echo "##         Installing as Symlink         ##"
    echo "###########################################"
    chmod +x ${DIR}/mq
    sudo rm -f /usr/bin/mq
    sudo rm -f /etc/bash_completion.d/mq
    sudo ln -sv ${DIR}/mq /usr/bin/mq
    sudo ln -sv /usr/bin/mq /etc/bash_completion.d/mq
    install_python
    echo
}


function install_cp {
    echo "##########################################"
    echo "##           Installing Files           ##"
    echo "##########################################"
    chmod +x ${DIR}/mq
    sudo rm -f /usr/bin/mq
    sudo rm -f /etc/bash_completion.d/mq
    sudo cp -fv ${DIR}/mq /usr/bin/mq
    sudo ln -sv /usr/bin/mq /etc/bash_completion.d/mq
    install_python
    echo
}


function update {
    echo "##########################################"
    echo "##        Pull in latest changes        ##"
    echo "##########################################"
    git pull origin master 
    install_python
}

#####################
##     Execute     ##
#####################

if [ "$1" == "link" ]; then
    install_link
elif [ "$1" == "copy" ]; then
    install_cp
elif [ "$1" == "update" ]; then
    update
else
    echo -n "Example INSTALL <TYPE>

    <TYPE> can be either:

        link        Installs as symlinks to this dir
        copy        Copies necessary files to destination
        update      Pulls the latest changes and updates your system
    "
    echo
fi

exit 0